FROM node:20-alpine AS builder
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install
COPY frontend/ ./
RUN npm run build

# ใช้ Nginx เพื่อเป็น Web Server
FROM nginx:alpine
# ก๊อปปี้ไฟล์ที่ build เสร็จแล้วไปไว้ใน Nginx (สมมติว่าสร้างไฟล์ไว้ในโฟลเดอร์ dist)
COPY --from=builder /app/dist /usr/share/nginx/html
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]